_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 19
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
adversarial_loss_coef:
    value: 0.01
batch_size:
    value: 256
buffer_size:
    value: 1000
causal_dim:
    value: 6
causal_hidden_dim:
    value: 128
config_path:
    value: /home/xi/yxh_space/SaMI/SaMI/output/PandaPush_obs22_object_size_6cm/SaCCM_trainenv_1_mix
contrast_batch_size:
    value: 256
contrast_buffer_type:
    value: fine_grained
contrast_training_interval:
    value: 1
encoder_tau:
    value: 0.05
env_hook:
    value: PandaHook
env_name:
    value: PandaPush-v3
gradient_steps:
    value: 16
learning_rate:
    value: 0.001
log_timeout:
    value: 10
method:
    value: SaCCM
neg_radio:
    value: 0.5
save_video:
    value: false
seed:
    value: 100
test_envs:
    value: '[(1,1)]'
test_eps_num_per_env:
    value: 2
time_step:
    value: 500000
train_envs:
    value: '[(1, 1),(1, 2),(1, 3),(1, 4),(1, 5),(1, 6),(1, 1),(1, 10)]'
train_freq:
    value: 128
use_continue_train:
    value: false
use_reward_norm:
    value: false
use_wandb:
    value: true
use_weighted_info_nce:
    value: false
wandb_project_name:
    value: franky-sami
wandb_team_name:
    value: skill-aware-rl
